#!/usr/bin/env node
/**
 * Generates APP_VERSION from git rev-list count.
 * Version format: 1.0, 1.1, 1.2 … (increments by 0.1 per commit).
 *
 * Skips writing when git history is not trustworthy (shallow clone, missing .git, CI hosts):
 * use committed src/generated/version.ts (updated by pre-commit hook locally).
 */

import { execSync } from "child_process";
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function isShallowClone() {
  try {
    return (
      execSync("git rev-parse --is-shallow-repository", { cwd: root, encoding: "utf8" }).trim() === "true"
    );
  } catch {
    return true;
  }
}

function shouldUseCommittedVersion() {
  if (process.env.VERCEL === "1") return "VERCEL";
  if (process.env.NETLIFY === "true") return "NETLIFY";
  if (process.env.CF_PAGES === "1") return "CF_PAGES";
  if (process.env.RAILWAY_ENVIRONMENT !== undefined) return "RAILWAY";
  if (isShallowClone()) return "shallow_clone";
  return null;
}

const skipReason = shouldUseCommittedVersion();
if (skipReason) {
  console.log(`[version] Skip generation (${skipReason}): using committed version.ts`);
  process.exit(0);
}

function getCommitCount() {
  try {
    const raw = execSync("git rev-list --count HEAD", { cwd: root, encoding: "utf8" }).trim();
    const n = parseInt(raw, 10);
    return Number.isFinite(n) && n >= 0 ? n : null;
  } catch {
    return null;
  }
}

const count = getCommitCount();
if (count === null) {
  console.log("[version] Skip generation (git rev-list failed): using committed version.ts");
  process.exit(0);
}
const version = `1.${count}`;
const outPath = join(root, "src", "generated", "version.ts");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-version.mjs — do not edit by hand
export const APP_VERSION = "${version}";
`,
  "utf8"
);
console.log("Version:", version);
