#!/usr/bin/env node
/**
 * Generates APP_VERSION from git rev-list count.
 * Version format: 1.0, 1.1, 1.2 … (increments by 0.1 per commit).
 *
 * On Vercel: skips generation — shallow clone makes rev-list wrong; use committed version.ts.
 */

import { execSync } from "child_process";
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

if (process.env.VERCEL === "1") {
  console.log("[version] Vercel: using committed version.ts (shallow clone)");
  process.exit(0);
}

function getCommitCount() {
  try {
    return parseInt(execSync("git rev-list --count HEAD", { cwd: root, encoding: "utf8" }).trim(), 10) || 0;
  } catch {
    return 0;
  }
}

const count = getCommitCount();
const version = `1.${count}`;
const outPath = join(root, "src", "generated", "version.ts");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-version.mjs — do not edit by hand
export const APP_VERSION = "${version}";
`,
  "utf8"
);
console.log("Version:", version);
